// Import the original config from the @wordpress/scripts package.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities.
const path = require('path');

// Add any a new entry point by extending the webpack config.
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      ...defaultConfig.entry,
      '../scripts/campaignbridge': path.resolve(
        process.cwd(),
        'src/scripts',
        'campaignbridge.js'
      ),
      '../styles/styles': path.resolve(
        process.cwd(),
        'src/styles',
        'styles.css'
      ),
    },
    plugins: [
      // Very important! Include WP's plugin config or the
      // world will cease to exist as we know it.
      ...defaultConfig.plugins,

      // Removes the empty `.js` files generated by webpack but
      // sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
      }),
    ],
  },
  cache: false,
};
