/**
 * CampaignBridge Post Card Block
 *
 * A versatile content container block for displaying post information in email campaigns.
 * This block serves as a wrapper for post-related content blocks (image, title, excerpt, CTA)
 * and provides post selection, linking, and styling capabilities.
 *
 * Features:
 * - Dynamic post selection from WordPress content
 * - Post type filtering and selection
 * - Optional link wrapper for entire card
 * - Inner blocks support for modular content composition
 * - Context provider for child blocks (post ID and type)
 * - Responsive design with border, shadow, and spacing support
 *
 * Use Cases:
 * - Featured post highlights in newsletters
 * - Post preview cards in email digests
 * - Content teasers with call-to-action buttons
 *
 * @module post-card
 */

import { InnerBlocks } from '@wordpress/block-editor';
import type { BlockConfiguration } from '@wordpress/blocks';
import { registerBlockType } from '@wordpress/blocks';
import React from 'react';

import metadata from './block.json';
import Edit from './edit';

/**
 * Block metadata imported from block.json
 */
export { metadata };

/**
 * Block name extracted from metadata
 */
export const { name }: { name: string } = metadata;

/**
 * Block settings configuration
 *
 * Defines the edit and save components for the post card block.
 */
export interface PostCardBlockSettings {
  edit: React.ComponentType<any>;
  save: () => JSX.Element;
}

export const settings: PostCardBlockSettings = {
  edit: Edit,
  /**
   * Save component for post card block
   *
   * Renders the InnerBlocks content placeholder for server-side rendering.
   * The actual HTML output is generated by the PHP render callback.
   */
  save() {
    return <InnerBlocks.Content />;
  },
};

/**
 * Initialize and register the post card block
 *
 * Registers the block with WordPress using the metadata and settings.
 * This function is called immediately to register the block on load.
 */
export const init = (): void => {
  registerBlockType(
    { name, ...metadata } as unknown as BlockConfiguration,
    settings
  );
};

// Initialize the block immediately
init();
